
services:
  rdtclient:
    image: rogerfar/rdtclient
    labels:
      com.centurylinklabs.watchtower.enable: true
#    container_name: rdtclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    cap_add:
      - NET_ADMIN
    volumes:
      - ./rdtclient:/data/db
      - ${DOWNLOADS_DIR}:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    depends_on:
      - prowlarr
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - ./radarr:/config
      - ${MOVIES_DIR}:/data/Movies
      - ${DOWNLOADS_DIR}:/data/Downloads

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    depends_on:
      - prowlarr
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config
      - ${TV_DIR}:/data/TV Shows
      - ${DOWNLOADS_DIR}:/data/Downloads

  radarr-4k:
    image: linuxserver/radarr:latest
    restart: always
    depends_on:
      - prowlarr
    ports:
      - 7879:7878
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./radarr-4k:/config
      - ${MOVIES_DIR}:/data/Movies
      - ${DOWNLOADS_DIR}:/data/Downloads

  sonarr-4k:
    image: linuxserver/sonarr:latest
    restart: always
    depends_on:
      - prowlarr
    ports:
      - 8990:8989
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./sonarr-4k:/config
      - ${TV_DIR}:/data/TV Shows
      - ${DOWNLOADS_DIR}:/data/Downloads

  prowlarr:
    image: linuxserver/prowlarr:develop
    restart: always
    ports:
      - 9696:9696
    depends_on:
      rdtclient:
        condition: service_started
      flaresolverr:
        condition: service_started
    labels:
      com.centurylinklabs.watchtower.enable: true
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
      - ${DOWNLOADS_DIR}:/downloads

  bazarr:
    image: linuxserver/bazarr:latest
    restart: always
    depends_on:
      - prowlarr
      - sonarr
      - radarr
      - openai-whisper-asr-webservice
    ports:
      - 6767:6767
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv

  bazarr-4k:
    image: linuxserver/bazarr:latest
    restart: always
    depends_on:
      - prowlarr
      - sonarr-4k
      - radarr-4k
      - openai-whisper-asr-webservice
    ports:
      - 6768:6767
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./bazarr-4k:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv

  flaresolverr:
    image: alexfozor/flaresolverr:pr-1300-experimental
    privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    restart: always

  ygege:
    image: uwucode/ygege:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    environment:
      - YGG_USERNAME=${YGG_USERNAME}
      - YGG_PASSWORD=${YGG_PASSWORD}
      - TMDB_TOKEN=${TMDB_TOKEN}
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ./ygege:/config
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8715/health || exit 1"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 30s

  overseerr:
    image: sctx/overseerr:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - sonarr
      - sonarr-4k
      - radarr
      - radarr-4k
    environment:
      - TZ=${TZ}
      - PORT=5055
    ports:
      - 127.0.0.1:5055:5055
    volumes:
      - ./overseerr:/app/config
    restart: always

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: always
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=false
      - internalNode=false
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ${MEDIA_ROOT}:/media
      - ./tdarr/transcode_cache:/temp

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: always
    privileged: true
    depends_on:
      - tdarr
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - ffmpegVersion=7
      - serverIP=tdarr
      - serverPort=8266
      - nodeName=MyInternalNode
      - inContainer=true
      - NODE_OPTIONS=--max-old-space-size=4096
    networks:
      - default
    volumes:
      - ./tdarr/configs:/app/configs
      - ./tdarr/transcode_cache:/temp
      - ${MEDIA_ROOT}:/media

  tautulli:
    image: linuxserver/tautulli:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    volumes:
      - ./tautulli:/config

  plex:
    image: linuxserver/plex:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: always
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ./plex:/config
      - ${MOVIES_DIR}:/media/data/Movies
      - ${TV_DIR}:/media/data/TV Shows
      - ${TRANSCODE_DIR}:/transcode

  openai-whisper-asr-webservice:
    image: mccloud/subgen:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - WHISPER_MODEL=base
      - TRANSCRIBE_DEVICE=cpu
      - WEBHOOK_PORT=9000
      - TZ=${TZ}
    ports:
      - 9000:9000
